# ========================================================
# orc-tieresias - Projeto Zephyr RTOS (Application Core)
# ========================================================

# 1. Habilitar Periféricos de Hardware (Sensores)
CONFIG_GPIO=y
CONFIG_I2C=y
CONFIG_ADC=y

# 2. Habilitar Log para Depuração (Alta Velocidade via RTT)
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_USE_SEGGER_RTT=y
CONFIG_LOG_BACKEND_RTT=y
CONFIG_LOG_BACKEND_UART=n

# 3. Barramento de Mensagens Interno (Zbus)
CONFIG_ZBUS=y
CONFIG_ZBUS_RUNTIME_OBSERVERS=y

# 4. Configurações Básicas do Bluetooth LE
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="orc-tieresias"
CONFIG_BT_DEVICE_APPEARANCE=833 
CONFIG_BT_GATT_CLIENT=n 

# 5. Expansão de Memória para as Threads
CONFIG_HEAP_MEM_POOL_SIZE=4096
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

# ====================================================================
# 6. HARDWARE E SENSORES (I2C + BMI270 + Ponto Flutuante)
# ====================================================================
CONFIG_SENSOR=y
CONFIG_BMI270=y
CONFIG_BMI270_TRIGGER_GLOBAL_THREAD=y 

# Obrigatório para o Filtro de Madgwick rodar em Threads
CONFIG_FPU=y
CONFIG_FPU_SHARING=y

# ========================================================
# 7. OTIMIZAÇÃO DE RÁDIO E BUFFERS (Alta Performance)
# ========================================================
# Tamanho máximo de pacote GATT
CONFIG_BT_L2CAP_TX_MTU=247
CONFIG_BT_GATT_AUTO_UPDATE_MTU=y

# Tamanho do pacote aéreo (DLE)
CONFIG_BT_BUF_ACL_RX_SIZE=251
CONFIG_BT_BUF_ACL_TX_SIZE=251
CONFIG_BT_USER_DATA_LEN_UPDATE=y


# PHY 2M (Dobra a velocidade de transmissão no ar)
CONFIG_BT_USER_PHY_UPDATE=y


# --- CORREÇÃO DA FILA DE PACOTES (TX/RX) ---
CONFIG_BT_BUF_ACL_TX_COUNT=20
CONFIG_BT_L2CAP_TX_BUF_COUNT=20
CONFIG_BT_CONN_TX_MAX=20

# A fila de eventos RX DEVE ser maior que a TX para evitar deadlock e dreno de bateria
CONFIG_BT_BUF_EVT_RX_COUNT=24
# --- INTERVALOS DE CONEXÃO AGRESSIVOS ---
# Força o pedido de atualização dos parâmetros de conexão
CONFIG_BT_GAP_AUTO_UPDATE_CONN_PARAMS=y

# Intervalo Mínimo: 6 unidades (6 * 1.25ms = 7.5ms)
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6

# Intervalo Máximo: 12 unidades (12 * 1.25ms = 15ms)
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=12

# Aumenta o limite de tempo antes de derrubar por falha
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=400
CONFIG_BT_GATT_CLIENT=y