# ========================================================
# orc-tieresias - Projeto Zephyr RTOS (Configurações base)
# ========================================================

# 1. Habilitar Periféricos de Hardware (Sensores)
CONFIG_GPIO=y
CONFIG_I2C=y
CONFIG_ADC=y
# Zbus
CONFIG_ZBUS=y

# 2. Habilitar Log para Depuração (Essencial para ler erros no terminal)
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_USE_SEGGER_RTT=y
CONFIG_LOG_BACKEND_RTT=y
CONFIG_LOG_BACKEND_UART=n

# 3. Configurações Básicas do Bluetooth LE
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="orc-tieresias"
# Apresentação genérica para o celular não tentar tratar como um fone de ouvido padrão
CONFIG_BT_DEVICE_APPEARANCE=833 

# 4. Expansão de Memória para as Threads
CONFIG_HEAP_MEM_POOL_SIZE=4096
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

# ========================================================
# 5. O SEGREDO DA VELOCIDADE E BATERIA (Data Length Extension)
# ========================================================
# Habilita o envio de pacotes longos (MTU estendido para caber nossos 15 frames)
CONFIG_BT_L2CAP_TX_MTU=247
CONFIG_BT_BUF_ACL_RX_SIZE=251
CONFIG_BT_BUF_ACL_TX_SIZE=251
CONFIG_BT_USER_DATA_LEN_UPDATE=y

# ========================================================
# 6. Barramento de Mensagens Interno
# ========================================================
CONFIG_ZBUS=y
CONFIG_ZBUS_RUNTIME_OBSERVERS=y

# ====================================================================
# OTIMIZAÇÃO DE BANDA (MTU EXPANDIDO PARA 4kHz AUDIO + TELEMETRIA)
# ====================================================================
CONFIG_BT_CTLR_DATA_LENGTH_MAX=251
CONFIG_BT_L2CAP_TX_MTU=247
CONFIG_BT_GATT_AUTO_UPDATE_MTU=y

# ====================================================================
# HARDWARE E SENSORES (I2C + BMI270)
# ====================================================================
CONFIG_SENSOR=y
CONFIG_BMI270=y
CONFIG_BMI270_TRIGGER_OWN_THREAD=y
CONFIG_BMI270_TRIGGER_GLOBAL_THREAD=y
CONFIG_FPU=y
CONFIG_FPU_SHARING=y

